### PR TITLE
Update geocode.R

### LINKED ISSUE #109: call_geolocator_latlon not working
Hello! 

I tried this same geo area on the census API web interface and got data back, but the call in tigris returned an NA. 

tigris::call_geolocator_latlon(33.70383, -84.69793)
 
I'm pretty sure this is because the api now uses the 2020 census blocks. 

length(response$result$geographies$`2010 Census Blocks`[[1]]$GEOID) is now NULL and should be 
length(response$result$geographies$`2020 Census Blocks`[[1]]$GEOID)

Happy to do a pull request if that's easier for you.

### PR DESCRIPTION
**Pull request by dteck**
I got an email about there being issues with this function. I see that you did a patch with fix #109. but it looks like the API swapped the X and Y for Latitude and Longitude. So calls were looking way outside of their intended area. And if the result isn't inside the states it just returns NULL for geography.
You can check out the web interface for this call here: 
https://geocoding.geo.census.gov/geocoder/geographies/coordinates?form

Also there was some question about the way it handles 2010 vs 2020 geographies in the JSON response. So I added some regex to avoid running into issues when people change the benchmark and vintage. Instead of coding in the year it just looks for "block" in the response and then sets a reference point for the rest of the code.

Let me know if you have any questions. 
Thanks

### CODE REVIEW

**Comment by dteck** [comment]
This second commit adds a new function that can make calls to the batch geocoding API. It takes a dataframe of address data and splits it into batches that it then saves as CSV files and uploads to the API one at a time. It then aggregates the results and returns the users dataframe with additional columns showing if there was a match, how exact the match was, the matched address, and the Lon/Lat coordinates. 

The web interface for this API call can be seen here:
https://geocoding.geo.census.gov/geocoder/geographies/addressbatch?form

**Comment by walkerke** [comment]
Excellent, thank you for your contributions!  I'll pull this down and review.

**Comment by dteck** [comment]
Sorry for the additional commit but I realized I had left the benchmark and vintage values hard coded in the API call rather than using the user input. I also added error handling for any failed api calls (any HTTP status that isn't 200). Otherwise the function would try to read a CSV that was just an error message and would hard crash. Now it shows an error message indicating a failed call and returns an NA.

**Comment by walkerke** [comment]
@dteck a heads up that I'm getting around to reviewing this PR - there are some conflicts I'm resolving which I'm working on over in https://github.com/walkerke/tigris/tree/dteck-master, so I'll keep you posted!

**Comment by walkerke** [comment]
Hi @dteck!  I've merged in your contributions to the existing code.  With respect to the batch geocoding function - would you mind documenting with roxygen2 in the style of the other functions in the package and using roxygen2 to generate the documentation, then submitting a new PR?  I've found the easiest way to get this set up is in RStudio to use `Code > Insert Roxygen Skeleton` and then documenting as in https://r-pkgs.org/man.html.

**Pull request merged**
